(function() { this.JST || (this.JST = {}); this.JST["templates/embed"] = function(obj){var __p=[],print=function(){__p.push.apply(__p,arguments);};with(obj||{}){__p.push('<script src="//cdnjs.cloudflare.com/ajax/libs/pym/0.4.1/pym.min.js"></script>\n<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>\n<style>\n\thtml, body {\n\t\tmargin: 0;\n\t\tpadding: 0;\n\t}\n\t\n\t.filmstrip-outer-wrapper {\n\t    width: 100%;\n\t    margin-bottom: 1em;\n\t}\n\n\t.filmstrip-wrapper {\n        max-width: 100%;\n    }\n\t \n    .filmstrip {\n        -webkit-animation-name: gif;\n    \t-webkit-animation-duration: 2s;\n\t    -webkit-animation-iteration-count: infinite;\n\t    -webkit-animation-timing-function: linear;\n\t    -webkit-animation-timing-function:steps(1, end);\n\t    background-repeat: no-repeat;\n\t    background-size: 100% auto;\n\t    z-index: 1000;\n    }\n\n    .filmstrip img {\n\t  visibility: hidden;\n\t  max-width: 100%; \n\t}\n\n    @-webkit-keyframes gif {\n    \t'); 
  	    var num_frames = imageUrls.length,
  	    frames_array = num_frames - 1,
  	    increment = Math.floor(100 / frames_array);
  
  		for (var i = 0; i < num_frames; i++) {
  			var frame_percentage = i * increment;
  			if ((i == frames_array) && (frame_percentage !== 100)) { ; __p.push('\n\t\t\t\t100% { background-image: url(\'',  imageUrls[i] ,'\');}\n\t\t\t');  } else { ; __p.push('\n\t\t\t\t',  frame_percentage ,'% { background-image: url(\'',  imageUrls[i] ,'\');}\n\t\t\t');  }
  		} ; __p.push('\n    }\n</style>\n\n<script>\n\t$(window).load(function() {\n\t\tvar pymChild = pym.Child();\n\t\tvar filmstrip_cotton = $(\'html\').find(\'.filmstrip-wrapper\');\n\t\tvar filmstrip_cotton_wrapper = $(\'html\').find(\'.filmstrip-outer-wrapper\');\n\t\tvar filmstrip_cotton_aspect_width = $(\'img\').width();\n\t\tvar filmstrip_cotton_aspect_height = $(\'img\').height();\n\n\t\tfunction size_filmstrip() {\n\t    \t$(\'.filmstrip img\').css({ \'height\' : ($(\'.filmstrip-outer-wrapper\').width() * $(\'img\').height() / $(\'img\').width())+\'px\'});\n\t    \tpymChild.sendHeight();\n\t\t}\n\n\t\tsize_filmstrip();\n\t\t\n\t\t$(window).resize(function() {\n\t\t\tsize_filmstrip();\n\t\t});\n\t});\n</script>\n\n<div class="filmstrip-outer-wrapper">\n\t<div class="filmstrip-wrapper">\n\t\t<div class="filmstrip animated">\n\t\t\t<img src="',  imageUrls[0] ,'" />\n\t\t</div>\n\t</div>\n</div>\n');}return __p.join('');};
}).call(this);
